language: ruby

env:
  - "RAILS_VERSION=4.2"
  - "RAILS_VERSION=5.2"
  - "RAILS_VERSION=master"

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3

matrix:
  fast_finish: true
  allow_failures:
    - env: "RAILS_VERSION=master"
  include:
    - rvm: 2.2
      env: RAILS_VERSION=4.2

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

before_script:
  - bundle exec rake app:db:setup

script: bundle exec rake spec
